### ISSUE TITLE
update-notifier wont start with appropiate persmissions

### ISSUE THREAD

**Issue by aemonge** [davidbrewer/xmonad-ubuntu-conf#11]
I know this isn't your fault nor responsibility. But you seam really smart, or at least smarter than me (:

I've setted this line in my *.xmonad/startup-hook*:
`update-notifier`

It does appears each time I log-in, but I can't update my software, nor change any config. I have to do all my updates over manual CLI.

Can you think in a way to use the GUI to keep my ubuntu up to date ?

TY

**Comment by davidbrewer** [comment]
Flattery will get you everywhere. (Although in reality, I cobbled this together from a variety of sources I found online and my understanding of it all is superficial at best, though I still use it daily!)

Personally I've been doing my updates via manual CLI and prefer it that way. It's possible that rationalization has kicked in since it seemed difficult to get the other way working.  :-)

As I understand it, a lot of the Gnome components like update-notifier expect other Gnome-related daemons to be running in the background. Sometimes I've found that running Nautilus to browse files causes something which didn't previously work to work temporarily for that session, which I think means that Nautilus launches some of the Gnome support daemons when you run it. You might be able to find out which specific Gnome components the update-notifier relies upon to work, and then add those to your startup-hook before you run update-notifier.

I just tried a couple things out. 
* When I run update-notifier, it seems like it may have worked, but I don't see any icon. This may be because there are no updates available right now though.
* When I run "update-manager", it does launch the update manager and seems to be working ok. Although again, I can't update at the moment because there are no updates available.

When you say that update-notifier appears at login, but you can't update your software... can you be more specific about where it's failing? Does the icon show up? Can you click on it? Does an interface for updating appear?

If you run update-manager directly, does that seem to work?

When I ran update-notifier,

**Comment by aemonge** [comment]
he he he he,

Well, it does launches and it seams ok. Actually I was pretty sure everything was working as expected. Till a month later, when I realised updates keep getting bigger. So that's when I realized that launching update-notifier (from startup-hook or directly from console) does nothing to actual updates.

Before your next update, try to do it via GUI. You'll see, everything shows as expected but non actual update will be done. 

But, it seams the problem is within gnome daemons not running correctly.......... I sounds like a pain in the A to search for thous specific daemons. So alternative, do you know a CLI command that automatically checks for your updates weekly, and ask you to updated them ( such as the oh-my-zsh, or the oh-my-bash, oh-my-X)

I have no direct love for update-notifier. I just don't want to manually keep in my mind, that I should update every-week.


Once again, thanks a LOT !! ^^

**Comment by davidbrewer** [comment]
Well that is sneaky and not very useful of it! I missed my shot to test this this morning, I will try to remember to take a look at it soon.

In the meantime, here are some ideas to explore on doing this via command line:
* Something like the cron-apt package might do at least part of the job for you. You can schedule it to check for and download new packages on a periodic basis, and if it finds any updates it will email you (well, it emails the root user... but there are ways you can set this up to redirect to an external address).
* Once you set up cron-apt, you could add something to your .bashrc or equivalent for your shell of preference which would display a notification if there were updated packages. A couple ideas here which you can try to see which output you prefer:
  * The following undocumented command may do the trick: `/usr/lib/update-notifier/apt-check -p --human-readable`
  * Or this: `apt list --upgradable`

Those last ideas would only make sense if you are a daily shell user, of course!

**Comment by davidbrewer** [comment]
Hmm. I did some updates by running update-manager today and they SEEM to have been applied for me. At least, when I run it again it doesn't find any additional updates, and when I use command-line apt it also doesn't find any additional updates.

**Comment by aemonge** [comment]
Ohhhh !!!! Coool, It did resolve my problem. With an easy echo, I'm being notified to update, xD

thanks a lot !!

**Comment by davidbrewer** [comment]
Glad I could help!
