### ISSUE TITLE
Possible issue and suggestions

### ISSUE THREAD

**Issue by shwsun** [davidbrewer/xmonad-ubuntu-conf#13]
Hi, 
I am using your config on ubuntu 16, it is very easy to setup and use, Great Work!

However, I have found some minor things bugging me. One of them is, I am a emacs user and `C-space` is blocked from usage. I tried to get rid of the line ` , ((myModMask.|. mod1Mask, xK_space), spawn "synapse")`, but I can still trigger synapse by `C-space`. And is there a way to make `Mod-p` as the default one and deal with the problem throughly?

**Comment by davidbrewer** [comment]
Hello! Apologies for late response on this -- I wanted to wait until I could spend a little time investigating to respond.

I believe the problem is not in the xmonad config itself, but in Synapse. If you launch Synapse, click on the little circle icon at the top right, and choose Preferences, you'll see that you can edit the keyboard shortcuts to launch Synapse. The first shortcut is "activate" -- this is the one that is set to C-space. If you change or delete this shortcut, you'll see that it now works as you want -- C-space is no longer taken by Synapse.

The problem is that when you log out and log back in, or otherwise close and restart Synapse, it resets all the settings! I haven't been able to find a way around this yet. There was an old bug about this issue which claims that the issue was fixed, but even though the version of Synapse I am using is much newer it still shows the same behavior.

I would definitely welcome any suggestions for how to work around this issue. I might investigate pulling out Synapse in favor of a launcher which is more consistently maintained. Other options might be mutate, alfred, gnome-do, or kupfer.

**Comment by shwsun** [comment]
@davidbrewer Thanks for you time. 

It did look like a bug of synapse, it would be fine at least if we can config that somewhere. One suggestion is` dmenu`, I have been using that with Xmonad on my arch linux and it works fine.

**Comment by shwsun** [comment]
@davidbrewer  Hey, I just took a little time to track the bug and actually it is fixed by the bleeding edge version - fix is just do 
```
sudo add-apt-repository ppa:synapse-core/testing
sudo apt update
sudo apt install synapse
```
