### ISSUE TITLE
Install script wrong path 

### ISSUE THREAD

**Issue by awb99** [davidbrewer/xmonad-ubuntu-conf#15]
Your install script copies the data from ~/.xmonad which works for you when all is installed. But to work from the repository you need to copy it from xmonad-ubuntu-conf

**Comment by shwsun** [comment]
Are you not `git clone https://github.com/davidbrewer/xmonad-ubuntu-conf ~/.xmonad` ?

**Comment by davidbrewer** [comment]
@shwsun has it right, I think -- my intention is that you would clone this straight to ~/.xmonad and work from there. Or even better, make a fork and then clone the fork so that you can make and save any customizations you want to do. 

I touch on this here (at least the part about putting it at ~/.xmonad): https://github.com/davidbrewer/xmonad-ubuntu-conf#checkout-repository
