### ISSUE TITLE
Report on testing for Ubuntu 16 and 17

### ISSUE THREAD

**Issue by shwsun** [davidbrewer/xmonad-ubuntu-conf#17]
I have just moved from Ubuntu16 to Ubuntu 17 (just to get the newest kernel), everything seems to be working fine.

**Comment by davidbrewer** [comment]
That is awesome news! Thanks for letting me know.

I'm going to stick with only "officially" supporting LTS releases (hah, like this project is big enough for anything to be "official"), but it's good to know that there are no breakers in this last release. It hasn't been too hard to keep it going since I think most of the big Ubuntu UI changes happen in Unity and/or Gnome and we're independent of that.  :-)
