### ISSUE TITLE
Upgrading notes to 18.04 in README

### ISSUE THREAD

**Issue by brownnrl** [davidbrewer/xmonad-ubuntu-conf#18]
First of all, thank you.  I had tried Xmonad out prior and just couldn't get over that initial resistance in the default configuration.  Trying to get a good config was just not a task I could tackle without knowing I would use it.  You made it easy.

I was using UB 16.04 LTS, and recently upgraded to 18.04 LTS.  I had your xmonad configs up prior with a small amount of customization.  After pulling down your repo changes, and restarting the session, I noticed that stalonetray and variety weren't working.  Also, synapse had a funky look with little black boxes.  I tried changing start-xmonad, but the changes didn't seem to take.  Finally, I realized that the start-xmonad wasn't being executed.  Copying the desktop file from your repo again into /usr/share/xsessions seems to have everything up and running correctly.

Maybe a small section on the few tasks that need to be done to "properly" handle a dist upgrade?

I can fork and PR if you'd like, but my ideas my be a bit more on the trial-and-error side.  I might also be missing something I should have done, but have not yet done.  :)

**Comment by jl2035** [comment]
Should this work out-of-the-box? I have a fresh Ubuntu 18.04 installation and xmonad does not start properly. I only see the desktop background and a mouse. No status bar. Mod+shift+enter and Ctrl+Space don't do anything :(

**Comment by davidbrewer** [comment]
Oh my gosh, very sorry to have missed this feedback for almost 2 years! :man_facepalming:  I'm not able to use Xmonad at work anymore so I don't give this the attention I'd like to. However, I DID just return to it to get it working properly on 20.04. Your comment was very helpful to me because I ran into exactly the same problem as you described here, and the fix was exactly as you described. No other significant change was needed for 20.04.

I've updated the README to document this: https://github.com/davidbrewer/xmonad-ubuntu-conf#oh-no-i-upgraded-ubuntu-and-everything-broke

Thanks very much for opening this issue, and I'm glad you found the configuration useful!
